//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SORGAIR.Properties.Lang {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SORGAIR.Properties.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Actual version is.
        /// </summary>
        public static string home_actualversionis {
            get {
                return ResourceManager.GetString("home_actualversionis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot be deleted.
        /// </summary>
        public static string home_cannotbedeleted {
            get {
                return ResourceManager.GetString("home_cannotbedeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This contest cannot be deleted, because it is loaded actually.
        /// </summary>
        public static string home_cannotbedeletedbecauseisloaded {
            get {
                return ResourceManager.GetString("home_cannotbedeletedbecauseisloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Really delete contest.
        /// </summary>
        public static string home_contest_deleting_question {
            get {
                return ResourceManager.GetString("home_contest_deleting_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Contest deleting.
        /// </summary>
        public static string home_contest_deleting_title {
            get {
                return ResourceManager.GetString("home_contest_deleting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Create new contest.
        /// </summary>
        public static string home_createnewcontest {
            get {
                return ResourceManager.GetString("home_createnewcontest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete selected contest.
        /// </summary>
        public static string home_deleteselectedcontest {
            get {
                return ResourceManager.GetString("home_deleteselectedcontest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Loading, please wait....
        /// </summary>
        public static string home_load_caption {
            get {
                return ResourceManager.GetString("home_load_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Its Done :).
        /// </summary>
        public static string home_load_complete {
            get {
                return ResourceManager.GetString("home_load_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Loading database.
        /// </summary>
        public static string home_load_database {
            get {
                return ResourceManager.GetString("home_load_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Loading some details.....
        /// </summary>
        public static string home_load_details {
            get {
                return ResourceManager.GetString("home_load_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Loading rounds ....
        /// </summary>
        public static string home_load_rounds {
            get {
                return ResourceManager.GetString("home_load_rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Loading rules....
        /// </summary>
        public static string home_load_rules {
            get {
                return ResourceManager.GetString("home_load_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Loading sounds....
        /// </summary>
        public static string home_load_sounds {
            get {
                return ResourceManager.GetString("home_load_sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Loading users....
        /// </summary>
        public static string home_load_users {
            get {
                return ResourceManager.GetString("home_load_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Load selected contest.
        /// </summary>
        public static string home_loadselectedcontest {
            get {
                return ResourceManager.GetString("home_loadselectedcontest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný News.
        /// </summary>
        public static string home_newscount {
            get {
                return ResourceManager.GetString("home_newscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Not everything is filled.
        /// </summary>
        public static string home_noteverythinkfilled {
            get {
                return ResourceManager.GetString("home_noteverythinkfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please select what u want delete.
        /// </summary>
        public static string home_nothing_selected_info {
            get {
                return ResourceManager.GetString("home_nothing_selected_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nothing selected.
        /// </summary>
        public static string home_nothing_selected_title {
            get {
                return ResourceManager.GetString("home_nothing_selected_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please fill all fields.
        /// </summary>
        public static string home_pleasefillallfields {
            get {
                return ResourceManager.GetString("home_pleasefillallfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This name already exists.
        /// </summary>
        public static string home_thisnamealreadyexist {
            get {
                return ResourceManager.GetString("home_thisnamealreadyexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Wrong name.
        /// </summary>
        public static string home_wrongname {
            get {
                return ResourceManager.GetString("home_wrongname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Your version is.
        /// </summary>
        public static string home_yourversionis {
            get {
                return ResourceManager.GetString("home_yourversionis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Audio and others.
        /// </summary>
        public static string menu_audioandothers {
            get {
                return ResourceManager.GetString("menu_audioandothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Competitors.
        /// </summary>
        public static string menu_competitors {
            get {
                return ResourceManager.GetString("menu_competitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Contest settings.
        /// </summary>
        public static string menu_contest_settings {
            get {
                return ResourceManager.GetString("menu_contest_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Details and statistics.
        /// </summary>
        public static string menu_detailstatistics {
            get {
                return ResourceManager.GetString("menu_detailstatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Finals.
        /// </summary>
        public static string menu_finals {
            get {
                return ResourceManager.GetString("menu_finals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hardware.
        /// </summary>
        public static string menu_hardware {
            get {
                return ResourceManager.GetString("menu_hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Homepage.
        /// </summary>
        public static string menu_homepage {
            get {
                return ResourceManager.GetString("menu_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný List of rounds.
        /// </summary>
        public static string menu_listofrounds {
            get {
                return ResourceManager.GetString("menu_listofrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Matrix.
        /// </summary>
        public static string menu_matrix {
            get {
                return ResourceManager.GetString("menu_matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Online.
        /// </summary>
        public static string menu_online {
            get {
                return ResourceManager.GetString("menu_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Results.
        /// </summary>
        public static string menu_results {
            get {
                return ResourceManager.GetString("menu_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Final results.
        /// </summary>
        public static string menu_results_final {
            get {
                return ResourceManager.GetString("menu_results_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Selected flight.
        /// </summary>
        public static string menu_selectedflight {
            get {
                return ResourceManager.GetString("menu_selectedflight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Selected round.
        /// </summary>
        public static string menu_selectedround {
            get {
                return ResourceManager.GetString("menu_selectedround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Teams.
        /// </summary>
        public static string menu_teams {
            get {
                return ResourceManager.GetString("menu_teams", resourceCulture);
            }
        }
    }
}
